### ISSUE TITLE
Interfaz agregar cita

### ISSUE THREAD

**Issue by EdgarAsdf** [EdgarAsdf/Agenda#1]

**Comment by EdgarAsdf** [comment]
Julio

**Comment by haroldbarra** [comment]
[formulario de agenda.zip](https://github.com/EdgarAsdf/Agenda/files/7656049/formulario.de.agenda.zip)

**Comment by haroldbarra** [comment]
[formulario de agenda (2).zip](https://github.com/EdgarAsdf/Agenda/files/7656075/formulario.de.agenda.2.zip)
